### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by jinglescode** [mnakanishi/TRCA-SSVEP#2]
By any chance you have, or you know of someone's implementation of TRCA in Python?

**Comment by Fulin-Wei** [comment]
I find a&nbsp;implemention TRCA algorithm for ssvep signal classification by python here,&nbsp;https://github.com/iuype/TRCA-SSVEP.&nbsp;According to the article list, maybe this is what you want, a rewritten version of MATLAB on TRCA.&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mnakanishi/TRCA-SSVEP"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月9日(星期三) 中午11:01
收件人:&nbsp;"mnakanishi/TRCA-SSVEP"<TRCA-SSVEP@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[mnakanishi/TRCA-SSVEP] Python version? (#2)





 
By any chance you have, or you know of someone's implementation of TRCA in Python?

**Comment by jinglescode** [comment]
@Fulin-Wei, I have found that too, and I got very different results from the Matlab version (this repo). Did you use https://github.com/iuype/TRCA-SSVEP and did it work for you (getting similar results compared to this Matlab version)?

@mnakanishi are you able to verify https://github.com/iuype/TRCA-SSVEP is implemented correctly with your datasets?

**Comment by gferraro2019** [comment]
Hello,

I have translated @mnakanishi Matlab tutorial in Python and I got the same results, if you both still interested I could do a quick PR and push it to the repo.

Thanks.

Regards.

**Comment by jinglescode** [comment]
Hi @gferraro2019, thanks for your work! I would like to have the codes if you have them. I'm not sure if @mnakanishi will respond or accept any PR.

**Comment by gferraro2019** [comment]
Hi @jinglescode, 
just to inform you that I published the Python tutorial on this link https://github.com/nbara/python-meegkit#4-task-related-component-analysis-trca. You will find a very useful library and a TRCA classifier in Python fashion.

**Comment by okbalefthanded** [comment]
Here's a python translation for TRCA and other BCI classification methods, based on Scikit-Learn API:
https://github.com/okbalefthanded/BCI-Baseline
